config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "search", to: "rides#search"

  resources :rides, only: [:index, :create, :show, :edit, :update] do
    resources :dangers, only: [:index, :new, :create]
    resources :parkings, only: [:new, :create, :index]
    
    get "parking", to: "hotspots#parking"
    get "pump", to: "hotspots#pump"
    get "repairer", to: "hotspots#repairer"
  end
end

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :user
  has_many :dangers
  has_one :parking

  validates :origin_latitude, :origin_longitude, :destination_address, presence: true

  geocoded_by :destination_address, latitude: :destination_latitude, longitude: :destination_longitude
  after_validation :geocode, if: :will_save_change_to_destination_address?
end

app/controllers/rides_controller.rb
require 'json'
require 'yaml'

class RidesController < ApplicationController
  before_action :set_ride, only: [:show, :edit, :update]

  def index
    @back_path = search_path
    @rides = Ride.select(:destination_address).order(created_at: :desc).map(&:destination_address).uniq
  end

  def search
    if @last_ride = current_user.rides.last
      @parking = @last_ride.parking
      @address_parking = @parking.address_parking if @parking
    end
    if params[:query].present?
      result = Geocoder.search(params[:query]).first.coordinates
      @ride = Ride.new
      @markers = [{ lat: result.first, lng: result.last }]
    end
  end

  def create
    @ride = Ride.new(ride_params)
    @ride.user = current_user
    if @ride.save
      redirect_to edit_ride_path(@ride)
    else
      render :search
    end
  end

  def edit
    @back_path = search_path

    waypoints = get_waypoints(@ride, 'cycling')
    @cycling_waypoints = get_waypoints(@ride, 'cycling')[0]['routes'][0]['geometry']['coordinates']
    @duration = (get_waypoints(@ride, 'cycling')[0]['routes'][0]['duration'] / 60).ceil
    if waypoints[0]['routes'].length > 1
      @cycling_waypoints_alt = get_waypoints(@ride, 'cycling')[0]['routes'][1]['geometry']['coordinates']
      @duration_alt = (get_waypoints(@ride, 'cycling')[0]['routes'][1]['duration'] / 60).ceil
    end
    @markers = [
      # { lat: @cycling_waypoints.first[1], lng: @cycling_waypoints.first[0] },
      { lat: @cycling_waypoints.last[1], lng: @cycling_waypoints.last[0] }
    ]
  end

  def update
    @ride.update(ride_params)
    redirect_to ride_path(@ride)
  end

  def show
    @back_path = edit_ride_path(@ride)

    @markers = [
      # { lat: @ride.origin_latitude, lng: @ride.origin_longitude, className: 'marker_origin' },
      { lat: @ride.destination_latitude, lng: @ride.destination_longitude, className: 'marker_show' }
    ]

    @danger = Danger.new
    @markers_danger = @ride.dangers.map do |danger|
      {
        lat: danger.latitude,
        lng: danger.longitude,
        cat: danger.category
      }
    end

    # afficher les danger sur la show
    @markers_dangers_list = Ride.all.map(&:dangers).flatten.map do |danger_list|
      {
        lat: danger_list.latitude,
        lng: danger_list.longitude,
        cat: danger_list.category
      }
    end

    # @distance = Geocoder::Calculations.distance_between([@ride.origin_latitude,@ride.origin_longitude], [@ride.destination_latitude, @ride.destination_longitude])
    if @ride.bike_friendly
      data = get_waypoints(@ride, 'cycling')
      @cycling_waypoints = data[0]['routes'][1]['geometry']['coordinates']
      @duration = (data[0]['routes'][1]['duration'] / 60).ceil
      @distance = data[0]['routes'][1]['distance'] / 1000
      @color = '#ef596e'
      @steps = data[0]['routes'][1]['legs'][0]['steps']
    else
      data = get_waypoints(@ride, 'cycling')
      @cycling_waypoints = data[0]['routes'][0]['geometry']['coordinates']
      @duration = (data[0]['routes'][0]['duration'] / 60).ceil
      @distance = data[0]['routes'][0]['distance'] / 1000
      @color = '#193c60'
      @steps = data[0]['routes'][0]['legs'][0]['steps']
    end

  end

  private

  def ride_params
    params.require(:ride).permit(:origin_latitude, :origin_longitude, :destination_address, :destination_longitude, :destination_latitude, :bike_friendly)
  end

  def set_ride
    @ride = Ride.find(params[:id])
  end
end

app/views/rides/edit.html.erb
<div id="map_edit"
  style="height: 100vh; width: 100vw;"
  data-cycling-waypoints="<%= @cycling_waypoints.to_json %>"
  data-cycling-waypoints-alt="<%= @cycling_waypoints_alt.to_json %>"
  data-duration="<%= @duration.to_json %>"
  data-duration-alt="<%= @duration_alt.to_json %>"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<div class="container blur-background bottom-menu">
  <div class="blur-wrapper"></div>
  <div class="row no-gutters justify-content-center bg-transparent">
    <div class="edit">
     <div class="">
      <% if @cycling_waypoints_alt %>
        <%= simple_form_for(@ride, html: { id: "edit_ride_32_friendly"}) do |f| %>
          <%= f.input :bike_friendly, input_html: { value: true, id: "ride_bike_friendly" }, as: :hidden %>
          <%= f.submit "J'ai le temps", class: "btn btn-cyclee btn-cool" %>
        <% end %>
      <% end %>
    </div>
    <div class="">
      <%= simple_form_for(@ride, html: { id: "edit_ride_32_unfriendly"}) do |f| %>
        <%= f.input :bike_friendly, input_html: { value: false, id: "ride_bike_unfriendly" }, as: :hidden %>
        <%= f.submit "Je suis pressé.e", class: "btn btn-cyclee btn-fast" %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/rides/index.html.erb
<div class="index_rides">
  <h3 class="mb-3 p-3 text-center">Mes recherches</h3>
  <% @rides.each do |ride| %>
    <div class="m-3 border-bottom">
      <ul>
        <%= link_to search_path(query: ride) do %>
          <li><p><%= ride %></p></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/rides/search.html.erb
<div id="map"
  style="height: 100vh; width: 100vw;"

  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>


<% if params[:query].present? %>
  <div class="pb-3 px-3 bottom-menu recap-address">
    <div class="d-flex flex-column align-items-center bd-highlight bg-white" style="border-radius: 20px;">
      <p class='text-address'>Vous avez cherché:</p>
      <p class="address text-center"><%= params[:query] %></p>
        <%= simple_form_for(@ride, html: {class: "mb-3"}) do |f| %>
          <%= f.input :origin_latitude, as: :hidden %>
          <%= f.input :origin_longitude, as: :hidden %>
          <%= f.input :destination_address, input_html: { value: params[:query]}, as: :hidden %>
          <div class="wrapper-btn">
            <%= f.submit "On y va !", class: "btn btn-cyclee btn-cool"%>
          </div>
        <% end %>
      <%= link_to "Je fais une nouvelle recherche", search_path  %>
    </div>
  </div>
<% else %>
  <div class="d-flex flex-column bd-highlight mb-3">
    <div class="blur-background bottom-menu">

      <div class="blur-wrapper"></div>

      <div class="row no-gutters">

        <%= form_tag search_path, class: "search-form", method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control", id: "search",
            placeholder: "Où allez-vous ?"
          %>
          <%= submit_tag "", class: "btn btn-secondary d-none" %>
        <% end %>

      </div>
    </div>
  </div>
<% end %>

<div class="modal fade" id="modalOneParking" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Je suis garé.e</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'parkings/index', parking: @address_parking %>
      </div>
    </div>
  </div>
</div>

app/views/rides/show.html.erb
<div id="map_show"
  style="width: 100vw; height: 100vh;"
  data-markers="<%= @markers.to_json %>"
  data-zoom="<%= params[:zoom] %>"
  data-center="<%= params[:center] %>"
  data-markers-danger="<%= @markers_danger.to_json %>"
  data-markers-dangers-list="<%= @markers_dangers_list.to_json %>"
  data-duration="<%= @duration.to_json %>"
  data-cycling-waypoints="<%= @cycling_waypoints.to_json %>"
  data-steps="<%= @steps.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  data-color="<%= @color %>">
</div>

<div class="blur-background bottom-menu">
  <div class="blur-wrapper"></div>
  <div class="row no-gutters d-flex justify-content-between align-items-center">
    <div class="btn-map-layers" data-toggle="modal" data-target="#modalHotspot">
      <i class="fas fa-layer-group text-white"></i>
    </div>

      <div class="time font-weight-light">
        <%= @duration.round %> min - <%= @distance.truncate(2) %> kms
      </div>

    <div id="post-content" data-toggle="modal" data-target="#modalDanger">
      <i class="fas fa-exclamation text-white btn btn-dangers"></i>
    </div>
  </div>
</div>

<!-- Modal Hotspots-->
<div class="modal fade" id="modalHotspot" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Autour de moi</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body affiche">
        <div id="post-content" class="d-flex align-items-center justify-content-start" data-toggle="modal" data-target="#modalInstructions">
          <div class="AffiDirection"></div>
          <p class="mb-0">Instructions</p>
        </div>
        <%= link_to ride_parking_path(@ride), class: "d-flex align-items-center justify-content-start" do %>
          <div class="AffiParking"></div>
          <p class="mb-0">Parkings</p>
        <% end %>
        <%= link_to ride_pump_path(@ride), class: "d-flex align-items-center justify-content-start" do %>
          <div class="AffiPump"></div>
          <p class="mb-0">Pompes</p>
        <% end %>
        <%= link_to ride_repairer_path(@ride), class: "d-flex align-items-center justify-content-start" do %>
          <div class="AffiRepair"></div>
          <p class="mb-0">Réparateurs</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Modal Dangers-->
<div class="modal fade" id="modalDanger" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Déclarer un danger</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'dangers/new', ride: @ride, danger: @danger %>
      </div>
    </div>
  </div>
</div>

<!-- Modal Instructions -->
<div class="modal fade" id="modalInstructions" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Instructions</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="instructions"></div>
      </div>
    </div>
  </div>
</div>